spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: test
      password: test
      roles: USER, ADMIN

logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
    type: trace